Project 1: setup and mobile version skeleton
Debas-31/dbus-portfolio pull request #1
Opened 2021-10-20 18:49 UTC by Debas-31

# Milestone 1: Setup and mobile version skeleton
>In this milestone of the project: 
- Added Header 
- Added Headline-section
- Added linters setup

2021-10-20 19:46 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️ 

Hi @Debas-31,

Good job so far!
✔️ Your linters are properly set up
✔️ Nice design
However, there are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-20 19:46 UTC, TedLivist commented on index.html
> +      <section class="headline-section">
- [ ] Please ensure that your **headline-section** is aligned with **`flexbox`**. In your CSS, that does not seem to be the case.

2021-10-20 19:46 UTC, TedLivist commented on index.html
> +              <ul class="lists"><li>Language</li>
- [ ] Please indent the **`li`** tag as it is a child of **`ul`**

2021-10-20 19:46 UTC, TedLivist commented on index.html
> +                <li>Bootsrap</li>
- [ ] In keeping with [HTML and CSS practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md) please fix your indentation here

2021-10-20 19:46 UTC, TedLivist commented on index.html
> +      </section>
- [ ] There seems to be an issue with the background image of your headline. According to the template, the circles should stretch across the screen but in your design that isn't the case. Please fix this. Look at the image below:

![debas-headline](https://user-images.githubusercontent.com/36542986/138159155-4bdc0666-a5bb-40d1-804e-84af689b19df.jpg)

- [ ] Going by the template, you are missing the headline icons. Please add them. **Note:** they should be wrapped in a `<ul>` tag with each of them being a link wrapped in a `<li>`

![debas-icons](https://user-images.githubusercontent.com/36542986/138159664-37bb975f-8ca5-4463-9da6-462b9335ddff.jpg)

2021-10-20 19:46 UTC, TedLivist commented on index.html
> +      <header>
- [ ] **[OPTIONAL]** Going by conventional, the **`main`** tag should not wrap your **`header`**. They are semantic tags with different purposes. The `<header>` can be a stand-alone element, while the `<main>` tag can wrap other parts of your main sections

2021-10-21 04:05 UTC, Alexoid1 approved these changes
# STATUS: APPROVED!!!
## Hi @Debas-31  Great job! 
## Congratulations :tada: Thanks for implementing changes suggested.
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! :tada:

# OPTIONAL

![brent-rambo-thumbs-up](https://user-images.githubusercontent.com/53111464/133719363-84d51903-9bd0-4ab2-94dd-7225d2862870.gif)


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-21 04:08 UTC, merged